skins.2=1
name.2=iregex:(Red Crewmate)

skins.3=2
name.3=iregex:(Blue Crewmate)

skins.4=3
name.4=iregex:(Green Crewmate)

skins.5=4
name.5=iregex:(Pink Crewmate)

skins.6=5
name.6=iregex:(Orange Crewmate)

skins.7=6
name.7=iregex:(Yellow Crewmate)

skins.8=7
name.8=iregex:(Grey Crewmate)

skins.9=8
name.9=iregex:(White Crewmate)

skins.10=9
name.10=iregex:(Purple Crewmate)

skins.11=10
name.11=iregex:(Brown Crewmate)

skins.12=11
name.12=iregex:(Cyan Crewmate)

skins.13=12
name.13=iregex:(Lime Crewmate)

skins.14=13
name.14=iregex:(Maroon Crewmate)

skins.15=14
name.15=iregex:(Rose Crewmate)

skins.16=15
name.16=iregex:(Banana Crewmate)

skins.17=16
name.17=iregex:(Gray Crewmate)

skins.18=17
name.18=iregex:(Tan Crewmate)

skins.19=18
name.19=iregex:(Coral Crewmate)

skins.20=1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
weights.20=3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
