skins.2=1
name.2=iregex:(Big Man)

skins.3=2
name.3=iregex:(Splatoween Big Man)

skins.4=3
name.4=iregex:(Frostyfest Big Man)

skins.5=4
name.5=iregex:(Springfest Big Man)

skins.6=5
name.6=iregex:(Summer Nights Big Man)

skins.7=2
biomes.7=crimson_forest warped_forest soul_sand_valley basalt_deltas nether_wastes

skins.8=3
biomes.8=snowy_plains ice_spikes grove snowy_slopes jagged_peaks frozen_peaks

skins.9=4
biomes.9=flower_forest

skins.10=4
biomes.10=beach desert

skins.11=1 2 3 4 5
weights.11=15 1 1 1 1
